<?php

namespace QuizBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsesRepository extends EntityRepository
{

    public function findById($id) {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r.status FROM QuizBundle:Responses r 
                      WHERE r.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }

    public function getAllByIdQuestions($id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT r FROM QuizBundle:Responses r
                      INNER JOIN QuizBundle:Questions q WITH r.idQuestion = q.id 
                      INNER JOIN QuizBundle:Themes t WITH q.idTheme = t.id 
                      WHERE t.id = :id'
            )
            ->setParameter('id', $id)
            ->getResult();
    }
}
