<?php

namespace QuizBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResponsesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsesRepository extends EntityRepository
{
}
