quiz:
    resource: "@QuizBundle/Controller/"
    type:     annotation
    prefix:   /

list_cat:
    path: /category/{id}
    defaults: { _controller: QuizBundle:Category:list }

app:
    resource: '@AppBundle/Controller/'
    type: annotation
