quiz:
    resource: "@QuizBundle/Controller/"
    type:     annotation
    prefix:   /

list_cat:
    path: /category/{id}
    defaults: { _controller: QuizBundle:Categories:list }

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /quiz_backend

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
